package enums;

public enum TipoMoneda
{
	UAE_Dirham("AED","UAE Dirham","Emiratos Árabes Unidos"),
	Afghani("AFN","Afghani","Afganistán"),
	Lek("ALL","Lek","Albania"),
	Armenian_Dram("AMD","Armenian Dram","Armenia"),
	Netherlands_Antillian_Guilder("ANG","Netherlands Antillian Guilder","Antillas Holandesas"),
	Kwanza("AOA","Kwanza","Angola"),
	Argentine_Peso("ARS","Argentine Peso","Argentina"),
	Australian_Dollar("AUD","Australian Dollar","Australia"),
	Aruban_Guilder("AWG","Aruban Guilder","Aruba"),
	Azerbaijanian_Manat("AZN","Azerbaijanian Manat","Azerbaiyán"),
	Convertible_Marks("BAM","Convertible Marks","Bosnia y Herzegovina"),
	Barbados_Dollar("BBD","Barbados Dollar","Barbados"),
	Taka("BDT","Taka","Bangladesh"),
	Bulgarian_Lev("BGN","Bulgarian Lev","Bulgaria"),
	Bahraini_Dinar("BHD","Bahraini Dinar","Bahréin"),
	Burundi_Franc("BIF","Burundi Franc","Burundi"),
	Bermudian_Dollar("BMD","Bermudian Dollar (customarily known as Bermuda Dollar)","Bermudas"),
	Brunei_Dollar("BND","Brunei Dollar","Brunéi Darussalam"),
	Boliviano("BOB","Boliviano","Bolivia"),
	Mvdol("BOV","Mvdol","Bolivia"),
	Brazilian_Real("BRL","Brazilian Real","Brasil"),
	Bahamian_Dollar("BSD","Bahamian Dollar","Bahamas"),
	Ngultrum("BTN","Ngultrum","Bután"),
	Pula("BWP","Pula","Botsuana"),
	Belarussian_Ruble("BYR","Belarussian Ruble","Bielorrusia"),
	Belize_Dollar("BZD","Belize Dollar","Belice"),
	Canadian_Dollar("CAD","Canadian Dollar","Canadá"),
	Congolese_Franc("CDF","Congolese Franc","República Democrática del Congo"),
	WIR_Euro("CHE","WIR Euro","Suiza"),
	Swiss_Franc("CHF","Swiss Franc","Suiza"),
	WIR_Franc("CHW","WIR Franc","Suiza"),
	Unidades_de_fomento("CLF","Unidades de fomento","Chile"),
	Chilean_Peso("CLP","Chilean Peso","Chile"),
	Yuan_Renminbi("CNY","Yuan Renminbi","China (República Popular)"),
	Colombian_Peso("COP","Colombian Peso","Colombia"),
	Unidad_de_Valor_Real("COU","Unidad de Valor Real","Colombia"),
	Costa_Rican_Colon("CRC","Costa Rican Colon","Costa Rica"),
	Peso_Convertible("CUC","Peso Convertible","Cuba"),
	Cuban_Peso("CUP","Cuban Peso","Cuba"),
	Cape_Verde_Escudo("CVE","Cape Verde Escudo","Cabo Verde"),
	Czech_Koruna("CZK","Czech Koruna","República Checa"),
	Djibouti_Franc("DJF","Djibouti Franc","Yibuti"),
	Danish_Krone("DKK","Danish Krone","Dinamarca"),
	Dominican_Peso("DOP","Dominican Peso","República Dominicana"),
	Algerian_Dinar("DZD","Algerian Dinar","Argelia"),
	Kroon("EEK","Kroon","Estonia"),
	Egyptian_Pound("EGP","Egyptian Pound","Egipto"),
	Nakfa("ERN","Nakfa","Eritrea"),
	Ethiopian_Birr("ETB","Ethiopian Birr","Etiopía"),
	Euro("EUR","Euro","Unión Europea"),
	Fiji_Dollar("FJD","Fiji Dollar","Fiyi"),
	Falkland_Islands_Pound("FKP","Falkland Islands Pound","Islas Malvinas"),
	Pound_Sterling("GBP","Pound Sterling","Reino Unido"),
	Lari("GEL","Lari","Georgia"),
	Cedi("GHS","Cedi","Ghana"),
	Gibraltar_Pound("GIP","Gibraltar Pound","Gibraltar"),
	Dalasi("GMD","Dalasi","Gambia"),
	Guinea_Franc("GNF","Guinea Franc","Guinea"),
	Quetzal("GTQ","Quetzal","Guatemala"),
	Guyana_Dollar("GYD","Guyana Dollar","Guyana"),
	Hong_Kong_Dollar("HKD","Hong Kong Dollar","Hong Kong"),
	Lempira("HNL","Lempira","Honduras"),
	Croatian_Kuna("HRK","Croatian Kuna","Croacia"),
	Gourde("HTG","Gourde","Haití"),
	Forint("HUF","Forint","Hungría"),
	Rupiah("IDR","Rupiah","Indonesia"),
	New_Israeli_Sheqel("ILS","New Israeli Sheqel","Israel"),
	Indian_Rupee("INR","Indian Rupee","India"),
	Iraqi_Dinar("IQD","Iraqi Dinar","Iraq"),
	Iranian_Rial("IRR","Iranian Rial","Irán"),
	Iceland_Krona("ISK","Iceland Krona","Islandia"),
	Jamaican_Dollar("JMD","Jamaican Dollar","Jamaica"),
	Jordanian_Dinar("JOD","Jordanian Dinar","Jordania"),
	Yen("JPY","Yen","Japón"),
	Kenyan_Shilling("KES","Kenyan Shilling","Kenia"),
	Som("KGS","Som","Kirguistán"),
	Riel("KHR","Riel","Camboya"),
	Comoro_Franc("KMF","Comoro Franc","Comoras"),
	North_Korean_Won("KPW","North Korean Won","Corea (del Norte)"),
	Won("KRW","Won","Corea (del Sur)"),
	Kuwaiti_Dinar("KWD","Kuwaiti Dinar","Kuwait"),
	Cayman_Islands_Dollar("KYD","Cayman Islands Dollar","Islas Caimán"),
	Tenge("KZT","Tenge","Kazajistán"),
	Kip("LAK","Kip","Laos"),
	Lebanese_Pound("LBP","Lebanese Pound","Líbano"),
	Sri_Lanka_Rupee("LKR","Sri Lanka Rupee","Sri Lanka"),
	Liberian_Dollar("LRD","Liberian Dollar","Liberia"),
	Loti("LSL","Loti","Lesoto"),
	Lithuanian_Litas("LTL","Lithuanian Litas","Lituania"),
	Latvian_Lats("LVL","Latvian Lats","Letonia"),
	Libyan_Dinar("LYD","Libyan Dinar","Libia"),
	Moroccan_Dirham("MAD","Moroccan Dirham","Marruecos"),
	Moldovan_Leu("MDL","Moldovan Leu","Moldavia"),
	Malagasy_Ariary("MGA","Malagasy Ariary","Madagascar"),
	Denar("MKD","Denar","Macedonia"),
	Kyat("MMK","Kyat","Myanmar (Birmania)"),
	Tugrik("MNT","Tugrik","Mongolia"),
	Pataca("MOP","Pataca","Macao"),
	Ouguiya("MRO","Ouguiya","Mauritania"),
	Mauritius_Rupee("MUR","Mauritius Rupee","Mauricio"),
	Rufiyaa("MVR","Rufiyaa","Maldivas"),
	Kwacha("MWK","Kwacha","Malaui"),
	Mexican_Peso("MXN","Mexican Peso","México"),
	Mexican_Unidad_de_Inversion("MXV","Mexican Unidad de Inversion (UDI)","México"),
	Malaysian_Ringgit("MYR","Malaysian Ringgit","Malasia"),
	Metical("MZN","Metical","Mozambique"),
	Namibia_Dollar("NAD","Namibia Dollar","Namibia"),
	Naira("NGN","Naira","Nigeria"),
	Cordoba_Oro("NIO","Cordoba Oro","Nicaragua"),
	Norwegian_Krone("NOK","Norwegian Krone","Noruega"),
	Nepalese_Rupee("NPR","Nepalese Rupee","Nepal"),
	New_Zealand_Dollar("NZD","New Zealand Dollar","Nueva Zelanda"),
	Rial_Omani("OMR","Rial Omani","Omán"),
	Balboa("PAB","Balboa","Panamá"),
	Nuevo_Sol_o_Sol("PEN","Nuevo Sol o Sol","Perú"),
	Kina("PGK","Kina","Papúa Nueva Guinea"),
	Philippine_Peso("PHP","Philippine Peso","Filipinas"),
	Pakistan_Rupee("PKR","Pakistan Rupee","Pakistán"),
	Zloty("PLN","Zloty","Polonia"),
	Guarani("PYG","Guarani","Paraguay"),
	Qatari_Rial("QAR","Qatari Rial","Qatar"),
	New_Leu("RON","New Leu","Rumania"),
	Serbian_Dinar("RSD","Serbian Dinar","Serbia"),
	Russian_Ruble("RUB","Russian Ruble","Rusia"),
	Rwanda_Franc("RWF","Rwanda Franc","Ruanda"),
	Saudi_Riyal("SAR","Saudi Riyal","Arabia Saudita"),
	Solomon_Islands_Dollar("SBD","Solomon Islands Dollar","Islas Salomón"),
	Seychelles_Rupee("SCR","Seychelles Rupee","Seychelles"),
	Sudanese_Pound("SDG","Sudanese Pound","Sudán"),
	Swedish_Krona("SEK","Swedish Krona","Suecia"),
	Singapore_Dollar("SGD","Singapore Dollar","Singapur"),
	Saint_Helena_Pound("SHP","Saint Helena Pound","Santa Helena"),
	Leone("SLL","Leone","Sierra Leona"),
	Somali_Shilling("SOS","Somali Shilling","Somalia"),
	Surinam_Dollar("SRD","Surinam Dollar","Surinam"),
	Dobra("STD","Dobra","Santo Tomé y Príncipe"),
	El_Salvador_Colon("SVC","El Salvador Colon","El Salvador"),
	Syrian_Pound("SYP","Syrian Pound","Siria"),
	Lilangeni("SZL","Lilangeni","Suazilandia"),
	Baht("THB","Baht","Tailandia"),
	Somoni("TJS","Somoni","Tayikistán"),
	Manat("TMT","Manat","Turkmenistán"),
	Tunisian_Dinar("TND","Tunisian Dinar","Túnez"),
	Pa_anga("TOP","Pa'anga","Tonga"),
	Turkish_Lira("TRY","Turkish Lira","Turquía"),
	Trinidad_and_Tobago_Dollar("TTD","Trinidad and Tobago Dollar","Trinidad y Tobago"),
	New_Taiwan_Dollar("TWD","New Taiwan Dollar","Taiwán"),
	Tanzanian_Shilling("TZS","Tanzanian Shilling","Tanzania"),
	Hryvnia("UAH","Hryvnia","Ucrania"),
	Uganda_Shilling("UGX","Uganda Shilling","Uganda"),
	US_Dollar_USD("USD","US Dollar","Estados Unidos (EEUU)"),
	US_Dollar_USN("USN","US Dollar (Next day)","Estados Unidos (EEUU)"),
	US_Dollar_USS("USS","US Dollar (Same day)","Estados Unidos (EEUU)"),
	Uruguay_Peso_en_Unidades_Indexadas("UYI","Uruguay Peso en Unidades Indexadas","Uruguay"),
	Peso_Uruguayo("UYU","Peso Uruguayo","Uruguay"),
	Uzbekistan_Sum("UZS","Uzbekistan Sum","Uzbekistán"),
	Bolivar_Fuerte("VEF","Bolivar Fuerte","Venezuela"),
	Dong("VND","Dong","Vietnam"),
	Vatu("VUV","Vatu","Vanuatu"),
	Tala("WST","Tala","Samoa del Oeste"),
	CFA_Franc_BEAC("XAF","CFA Franc BEAC ‡","-"),
	Silver("XAG","Silver","-"),
	Gold("XAU","Gold","-"),
	Bond_Markets_Units_European_Composite_Unit_("XBA","Bond Markets Units European Composite Unit (EURCO)","-"),
	European_Monetary_Unit("XBB","European Monetary Unit (E.M.U.-6)","-"),
	European_Unit_of_Account_9("XBC","European Unit of Account 9(E.U.A.-9)","-"),
	European_Unit_of_Account_17("XBD","European Unit of Account 17(E.U.A.-17)","-"),
	East_Caribbean_Dollar("XCD","East Caribbean Dollar","-"),
	SDR("XDR","SDR","-"),
	UIC_Franc("XFU","UIC-Franc","-"),
	CFA_Franc_BCEAO("XOF","CFA Franc BCEAO","-"),
	Palladium("XPD","Palladium","-"),
	CFP_Franc("XPF","CFP Franc","-"),
	Platinum("XPT","Platinum","-"),
	Yemeni_Rial("YER","Yemeni Rial","Yemen"),
	Rand("ZAR","Rand","Sudáfrica"),
	Zambian_Kwacha("ZMK","Zambian Kwacha","Zambia"),
	Zimbabwe_Dollar("ZWL","Zimbabwe Dollar","Zimbabue");
	
	private final String codigo;
	private final String descripcion;
	private final String pais;
	TipoMoneda(String codigo,String descripcion,String pais)
	{
		this.codigo=codigo;
		this.descripcion=descripcion;
		this.pais=pais;
	}
}
