package enums;

public enum TipoDeMedioDePago 
{
	DEPOSITO_EN_CUENTA("001","DEPÓSITO EN CUENTA"),
	GIRO("002","GIRO"),
	TRANSFERENCIA_DE_FONDOS("003","TRANSFERENCIA DE FONDOS"),
	ORDEN_DE_PAGO("004","ORDEN DE PAGO"),
	TARJETA_DE_DEBITO("005","TARJETA DE DÉBITO"),
	TARJETA_DE_CREDITO("006","TARJETA DE CRÉDITO EMITIDA EN EL PAÍS POR UNA EMPRESA DEL SISTEMA FINANCIERO"),
	CHEQUES("007","CHEQUES CON LA CLÁUSULA DE \"NO NEGOCIABLE\", \"INTRANSFERIBLES\", \"NO A LA ORDEN\" U OTRA EQUIVALENTE, A QUE SE REFIERE EL INCISO G) DEL ARTICULO 5° DE LA LEY"),
	EFECTIVO_OPERACIONES_SIN_OBLIGACION_DE_MEDIO_DE_PAGO("008","EFECTIVO, POR OPERACIONES EN LAS QUE NO EXISTE OBLIGACIÓN DE UTILIZAR MEDIO DE PAGO"),
	EFECTIVO_DEMAS_CASOS("009","EFECTIVO, EN LOS DEMÁS CASOS"),
	MEDIOS_DE_PAGO_USADOS_EN_COMERCIO_EXTERIOR("010","MEDIOS DE PAGO USADOS EN COMERCIO EXTERIOR"),
	DOCUMENTOS_EMITIDOS_POR_EDPYMES_Y_CAJAS("011","DOCUMENTOS EMITIDOS POR LAS EDPYMES Y LAS COOPERATIVAS DE AHORRO Y CRÉDITO NO AUTORIZADAS A CAPTAR DEPÓSITOS DEL PÚBLICO"),
	TARJETA_DE_CREDITO_NO_PERTENECIENTE_AL_SISTEMA_FINANCIERO("012","TARJETA DE CRÉDITO EMITIDA EN EL PAÍS O EN EL EXTERIOR POR UNA EMPRESA NO PERTENECIENTE AL SISTEMA FINANCIERO, CUYO OBJETO PRINCIPAL SEA LA EMISIÓN Y ADMINISTRACIÓN DE TARJETAS DE CRÉDITO"),
	TARJETA_DE_CREDITO_EMITIDA_EN_EL_EXTERIOR("013","TARJETAS DE CRÉDITO EMITIDAS EN EL EXTERIOR POR EMPRESAS BANCARIAS O FINANCIERAS NO DOMICILIADAS"),
	TRANSFERENCIAS("101","TRANSFERENCIAS - COMERCIO EXTERIOR"),
	CHEQUES_BANCARIOS("102","CHEQUES BANCARIOS  - COMERCIO EXTERIOR"),
	ORDEN_DE_PAGO_SIMPLE("103","ORDEN DE PAGO SIMPLE  - COMERCIO EXTERIOR"),
	ORDEN_DE_PAGO_DOCUMENTARIO("104","ORDEN DE PAGO DOCUMENTARIO  - COMERCIO EXTERIOR"),
	REMESA_SIMPLE("105","REMESA SIMPLE  - COMERCIO EXTERIOR"),
	REMESA_DOCUMENTARIA("106","REMESA DOCUMENTARIA  - COMERCIO EXTERIOR"),
	CARTA_DE_CREDITO_SIMPLE("107","CARTA DE CRÉDITO SIMPLE  - COMERCIO EXTERIOR"),
	CARTA_DE_CREDITO_DOCUMENTARIO("108","CARTA DE CRÉDITO DOCUMENTARIO  - COMERCIO EXTERIOR"),
	OTROS_MEDIOS_PAGO("999","OTROS MEDIOS DE PAGO");

	private final String numero;
	private final String descripcion;
	 TipoDeMedioDePago(String numero,String descripcion)
	{
		this.numero=numero;
		this.descripcion=descripcion;
	}
}
